### ISSUE TITLE
Project-Wide Style, Structure and Static Type Checking

### ISSUE THREAD

**Issue by Jacob-Chmura** [shenyangHuang/openDG#3]
Creating this issue to open up the discussion on how we want to manage the project-wide style, lining, static analysis, etc, for `OpenDG`.

Some tools I think might be worth considering
- Static Analysis: [mypy](https://mypy.readthedocs.io/en/stable/index.html)
- Linting / Formatting: [ruff](https://github.com/astral-sh/ruff)
- Other: [isort](https://pycqa.github.io/isort/), [flake8](https://flake8.pycqa.org/en/latest/)

I don't want to burden the quick iteration of `OpenDG` with unnecessary checks, but it's often easier to start development with these tools implemented early. Particularly to reduce review time on PR's.

**Comment by shenyangHuang** [comment]
I agree, it would be a good idea to start early with these set-ups.
